/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pro.vinicius.projetofliperama.view;

import br.pro.vinicius.projetofliperama.data.Conexao;
import br.pro.vinicius.projetofliperama.model.UsuarioModel;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;


/**
 *
 * @author Vinícius
 */
public class JFPrincipal extends javax.swing.JFrame {

        
    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }
        public JFPrincipal(UsuarioModel obj) {
            initComponents();
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jmPrincipal = new javax.swing.JMenuBar();
        jmiCadastros = new javax.swing.JMenu();
        jmiPlataforma = new javax.swing.JMenuItem();
        jmiGenero = new javax.swing.JMenuItem();
        jmiJogos = new javax.swing.JMenuItem();
        jmiJogador = new javax.swing.JMenuItem();
        jmiTelefones = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();
        jmiEmprestimos = new javax.swing.JMenu();
        jmiEmpresto = new javax.swing.JMenuItem();
        jmiRelatorios = new javax.swing.JMenu();
        jmiJogosAlugados = new javax.swing.JMenuItem();
        jmiClientesCad = new javax.swing.JMenuItem();
        jmiJogosCad = new javax.swing.JMenuItem();
        jmiPlataformasCad = new javax.swing.JMenuItem();
        jmiGeneros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.setAlignmentX(0.0F);
        jdpPrincipal.setAlignmentY(0.0F);
        jdpPrincipal.setPreferredSize(new java.awt.Dimension(1200, 705));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/vinicius/projetofliperama/imagens/melhores-jogos-fliperama-1200x705.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jdpPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmPrincipal.setAlignmentX(0.0F);

        jmiCadastros.setText("Cadastros");

        jmiPlataforma.setText("Plataforma");
        jmiPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPlataformaActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiPlataforma);

        jmiGenero.setText("Gênero");
        jmiGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGeneroActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiGenero);

        jmiJogos.setText("Jogos");
        jmiJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJogosActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiJogos);

        jmiJogador.setText("Jogador");
        jmiJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJogadorActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiJogador);

        jmiTelefones.setText("Telefones");
        jmiTelefones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTelefonesActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiTelefones);
        jmiCadastros.add(jSeparator1);

        jmiSair.setText("Sair");
        jmiCadastros.add(jmiSair);

        jmPrincipal.add(jmiCadastros);

        jmiEmprestimos.setText("Emprestimos");
        jmiEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmprestimosActionPerformed(evt);
            }
        });

        jmiEmpresto.setText("Empréstimos");
        jmiEmpresto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmprestoActionPerformed(evt);
            }
        });
        jmiEmprestimos.add(jmiEmpresto);

        jmPrincipal.add(jmiEmprestimos);

        jmiRelatorios.setText("Relatórios");
        jmiRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatoriosActionPerformed(evt);
            }
        });

        jmiJogosAlugados.setText("Jogos Alugados");
        jmiJogosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJogosAlugadosActionPerformed(evt);
            }
        });
        jmiRelatorios.add(jmiJogosAlugados);

        jmiClientesCad.setText("Clientes Cadastrados");
        jmiClientesCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesCadActionPerformed(evt);
            }
        });
        jmiRelatorios.add(jmiClientesCad);

        jmiJogosCad.setText("Jogos Cadastrados");
        jmiJogosCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJogosCadActionPerformed(evt);
            }
        });
        jmiRelatorios.add(jmiJogosCad);

        jmiPlataformasCad.setText("Plataformas");
        jmiPlataformasCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPlataformasCadActionPerformed(evt);
            }
        });
        jmiRelatorios.add(jmiPlataformasCad);

        jmiGeneros.setText("Gêneros");
        jmiGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGenerosActionPerformed(evt);
            }
        });
        jmiRelatorios.add(jmiGeneros);

        jmPrincipal.add(jmiRelatorios);

        setJMenuBar(jmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJogadorActionPerformed
        JIFJogador janela = new JIFJogador();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiJogadorActionPerformed

    private void jmiPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPlataformaActionPerformed
        JIFPlataforma janela = new JIFPlataforma();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiPlataformaActionPerformed

    private void jmiGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGeneroActionPerformed
        JIFGenero janela = new JIFGenero();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiGeneroActionPerformed

    private void jmiJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJogosActionPerformed
        JIFJogo janela = new JIFJogo();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiJogosActionPerformed

    private void jmiTelefonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTelefonesActionPerformed
        JIFTelefone janela = new JIFTelefone();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiTelefonesActionPerformed

    private void jmiEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmprestimosActionPerformed
        
    }//GEN-LAST:event_jmiEmprestimosActionPerformed

    private void jmiEmprestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmprestoActionPerformed
        JIFEmprestimo janela = new JIFEmprestimo();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiEmprestoActionPerformed

    private void jmiJogosAlugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJogosAlugadosActionPerformed
        try {
            Conexao conexao = new Conexao();
            Connection con = conexao.getConexao();
        // chama relatorio de jogos alugados
        //se quer imprimir
        int confirma = JOptionPane.showConfirmDialog(null, "Dejesa imprimir o relatório?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo
            String src = "C:/Users/Vinicius/Documents/NetBeansProjects/ProjetoFliperama/src/br/pro/vinicius/projetofliperama/relatorios/Emprestimos.jasper";
            
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src,null,con);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao gerar relatório \n" + ex);
            }
            JasperViewer view = new JasperViewer(jasperPrint,false);   
            view.setVisible(true);
        }
        
        } catch (Exception ex) {
            
        }
        
    }//GEN-LAST:event_jmiJogosAlugadosActionPerformed

    private void jmiClientesCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesCadActionPerformed
        try {
            Conexao conexao = new Conexao();
            Connection con = conexao.getConexao();
        

        // chama relatorio de jogos alugados
        //se quer imprimir
        int confirma = JOptionPane.showConfirmDialog(null, "Dejesa imprimir o relatório?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo
            String src = "C:/Users/Vinicius/Documents/NetBeansProjects/ProjetoFliperama/src/br/pro/vinicius/projetofliperama/relatorios/Clientes.jasper";
            
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src,null,con);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao gerar relatório \n" + ex);
            }
            JasperViewer view = new JasperViewer(jasperPrint,false);   
            view.setVisible(true);
        }
        
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jmiClientesCadActionPerformed

    private void jmiJogosCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJogosCadActionPerformed
        try {
            Conexao conexao = new Conexao();
            Connection con = conexao.getConexao();
        

        // chama relatorio de jogos alugados
        //se quer imprimir
        int confirma = JOptionPane.showConfirmDialog(null, "Dejesa imprimir o relatório?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo
            String src = "C:/Users/Vinicius/Documents/NetBeansProjects/ProjetoFliperama/src/br/pro/vinicius/projetofliperama/relatorios/Jogos.jasper";
            
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src,null,con);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao gerar relatório \n" + ex);
            }
            JasperViewer view = new JasperViewer(jasperPrint,false);   
            view.setVisible(true);
        }
        
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jmiJogosCadActionPerformed

    private void jmiRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatoriosActionPerformed
        
    }//GEN-LAST:event_jmiRelatoriosActionPerformed

    private void jmiPlataformasCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPlataformasCadActionPerformed
        try {
            Conexao conexao = new Conexao();
            Connection con = conexao.getConexao();
        

        // chama relatorio de jogos alugados
        //se quer imprimir
        int confirma = JOptionPane.showConfirmDialog(null, "Dejesa imprimir o relatório?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo
            String src = "C:/Users/Vinicius/Documents/NetBeansProjects/ProjetoFliperama/src/br/pro/vinicius/projetofliperama/relatorios/Plataformas.jasper";
            
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src,null,con);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao gerar relatório \n" + ex);
            }
            JasperViewer view = new JasperViewer(jasperPrint,false);   
            view.setVisible(true);
        }
        
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jmiPlataformasCadActionPerformed

    private void jmiGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGenerosActionPerformed
        try {
            Conexao conexao = new Conexao();
            Connection con = conexao.getConexao();
        

        // chama relatorio de jogos alugados
        //se quer imprimir
        int confirma = JOptionPane.showConfirmDialog(null, "Dejesa imprimir o relatório?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo
            String src = "C:/Users/Vinicius/Documents/NetBeansProjects/ProjetoFliperama/src/br/pro/vinicius/projetofliperama/relatorios/Generos.jasper";
            
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src,null,con);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao gerar relatório \n" + ex);
            }
            JasperViewer view = new JasperViewer(jasperPrint,false);   
            view.setVisible(true);
        }
        
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jmiGenerosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuBar jmPrincipal;
    private javax.swing.JMenu jmiCadastros;
    private javax.swing.JMenuItem jmiClientesCad;
    private javax.swing.JMenu jmiEmprestimos;
    private javax.swing.JMenuItem jmiEmpresto;
    private javax.swing.JMenuItem jmiGenero;
    private javax.swing.JMenuItem jmiGeneros;
    private javax.swing.JMenuItem jmiJogador;
    private javax.swing.JMenuItem jmiJogos;
    private javax.swing.JMenuItem jmiJogosAlugados;
    private javax.swing.JMenuItem jmiJogosCad;
    private javax.swing.JMenuItem jmiPlataforma;
    private javax.swing.JMenuItem jmiPlataformasCad;
    private javax.swing.JMenu jmiRelatorios;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiTelefones;
    // End of variables declaration//GEN-END:variables
}
