/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pro.vinicius.projetofliperama.view;

import br.pro.vinicius.projetofliperama.data.UsuarioData;
import br.pro.vinicius.projetofliperama.model.UsuarioModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinícius
 */
public class jifCadastroUsuario extends javax.swing.JInternalFrame {
    
    UsuarioModel obj;
    UsuarioData DAO;

    /**
     * Creates new form jifCadastroUsuario
     */
    public jifCadastroUsuario() {
        initComponents();
        try {
        obj = new UsuarioModel();
        DAO = new UsuarioData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbRegistrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jpfSenha = new javax.swing.JPasswordField();
        jbEditar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar");

        jLabel2.setText("Login");

        jLabel3.setText("Senha");

        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbEditar.setText("Alterar senha");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtLogin)
                            .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbRegistrar)
                        .addGap(123, 123, 123)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar)
                        .addGap(34, 34, 34)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRegistrar)
                    .addComponent(jbCancelar)
                    .addComponent(jbEditar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        try {
            if(validarCampos()){
                if(preencherObjeto()){
                        if(DAO.incluir(obj)){
                            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
                            jbCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao cadastrar ou usuario já existente");
                    }    
                }
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um Erro: " +e.getMessage());
        }
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        br.pro.vinicius.projetofliperama.extras.Formularios.limparCampos(this);
        br.pro.vinicius.projetofliperama.extras.Formularios.tratarCampos(this, false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        try {
            if(validarCampos()){
                if(preencherObjeto()){
                        if(DAO.editar(obj)){
                            JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
                            jbCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao atualizar");
                    }    
                }
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um Erro: " +e.getMessage());
        }
    }//GEN-LAST:event_jbEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtLogin;
    // End of variables declaration//GEN-END:variables
public boolean validarCampos(){
    if(jtLogin.getText().length() == 0){
        JOptionPane.showMessageDialog(this, "Digite o login");
        return false;
    }
    if(jpfSenha.getText().length() == 0){
        JOptionPane.showMessageDialog(this, "Digite a senha");
        return false;
    }
    return true;
}

    private boolean preencherObjeto()throws Exception{
    obj.setLogin(jtLogin.getText());
    obj.setSenha(jpfSenha.getText());   
    return true;
}

}
